server:
  port: 8001
  
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##NEWWORKER
    password: NEWWORKER
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
# 이메일 인증 코드를 담을 redis 서버 설정      

      
# 정적 리소스 경로 설정
  web:
    resources:
      static-locations: classpath:/uploadFiles/ #리소스 경로 더 추가하고 싶을 경우 , 찍어서 추가하세요
      
# jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]': true   

# email config
  mail:
    host: smtp.gmail.com
    port: 587
    username: newworker9999@gmail.com
    password: qjxjortzvjhsjjbq
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 이미지 저장할 위치와 응답 시 이미지 주소 설정
file:
  add-resource-locations: classpath:/static/uploadFiles/
  add-resource-handler: /uploadFiles/**
  file-dir: src/main/resources/static/uploadFiles #Service에서 자기 이미지 담을 하위 경로를 가공하세요!
  file-url: http://localhost:8001/uploadFiles #이하 동일입니다!


jwt:
  secret: rmNdxF4HeCNvC70Z6JEN8uUMBzCBxgIQ/aOcLN9/qKp5ZxhWzyGcmfY5T09Xgx18ibWU9qW3/sYZwWH+fCNv2w==
 

  
  